name: CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        java: [ '17' ]
        os: [ 'ubuntu-latest' ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
      with:
        repository: liatrio/run-gatling
        ref: v1.1.3

    - uses: liatrio/run-gatling@v1.1.3
      with:
          testPath: ./

    - name: debug
      if: ${{ always() }}
      run: ls -la